[project]
name = "ai-agent-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "functions-framework>=3.8.3",
    "line-bot-sdk>=3.17.1",
]
