max_token: 4096  # Default max tokens for gpt-4, can be adjusted
temperature: 0.7  # Default temperature for creativity level
model: "gpt-4o-mini-2024-07-18"  # Default model, can be changed to gpt-4 or others
date_diff_threshold: 5  # Default threshold for date difference in days
